<?php
// module/Recipe/view/recipe/recipe/addrecipe.phtml:

$title = 'Add new recipe';
$this->headTitle($title);
?>

    <h1><?php echo $this->escapeHtml($title); ?></h1>
<?php
//$form->setAttribute('action', $this->url(
//    'application',
//    array(
//        'action' => 'createcategory'
//    )
//));
$form->prepare();

echo $this->form()->openTag($form);
echo $this->formHidden($form->get('id')) . '</br>';
echo $this->formRow($form->get('recipeName')) . '</br>';
echo $this->formRow($form->get('description')) . '</br>';
echo $this->formRow($form->get('time')) . '</br>';
echo $this->formRow($form->get('idUser')) . '</br>';
echo $this->formSubmit($form->get('submit')) . '</br>';
echo $this->form()->closeTag();